### ISSUE TITLE
Settings - allow access flow is broken

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#168]

**Comment by samuelli** [comment]
There appears to be a few different factors in play here:
- The GraphQL API query for a viewer's organizations only displays the public organizations that you are a part of.
- In some cases, we can see that you are a public member of an organization, have read access, but the organization has an Access Restricted policy, which prevents the OAuth app from executing any queries against it. AFAIK, there's no way to determine via the app, that we don't have access beyond just trying a query and it fails.

**Comment by gauntface** [comment]
Relevant issue: https://platform.github.community/t/unable-to-list-user-organizations/4163/10

Hopefully this will change in the future, but for now we'll just remove the org from the list.
