### ISSUE TITLE
No status messages if the pullrequest is closed

### ISSUE THREAD

**Issue by gauntface** [PolymerLabs/project-health#195]
During the testing of the dashboard flashes I was getting a tonne of status notifications after the PR was closed.

**Comment by samuelli** [comment]
Can you provide more detail please?

**Comment by gauntface** [comment]
If a developer opens and closes a PR, the status hooks will be received by the server and result a notification is the build fails. Since the status of the PR is closed, we should avoid sending a notification.

**Comment by gauntface** [comment]
This is actually fixed in the code base so closing this.
