### ISSUE TITLE
Show status information for my outgoing PRs

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#207]

**Comment by gauntface** [comment]
How should status information be shown?

Looking at the mocks I can't see anywhere that this should be called out.

**Comment by samuelli** [comment]
Initially, it should affect the status field in the API.

https://github.com/PolymerLabs/project-health/blob/51d547cba10c86907382ee128a7e8e5b33c3da63/src/types/api.ts#L78-L81

https://github.com/PolymerLabs/project-health/blob/51d547cba10c86907382ee128a7e8e5b33c3da63/src/types/api.ts#L102-L104

We currently don't use this. I'll look into whether or not we want to add more UI affordance, but this should be more sufficient for now. Note the UI has already been handled with the status strings.
