### ISSUE TITLE
[Issue] Duplicate notification

### ISSUE THREAD

**Issue by gauntface** [PolymerLabs/project-health#213]
Might be due to multiple hooks.

![unnamed](https://user-images.githubusercontent.com/139760/36811699-8d3e0d66-1c83-11e8-8ed7-ad26f7c72327.png)

**Comment by merlinnot** [comment]
If you’re using Firebase Cloud Messaging, such bug has been fixed in the latest release: https://firebase.google.com/support/release-notes/js#4.10.1
