### ISSUE TITLE
Error on webhook

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#222]
A  POST 500 222 B 188 ms GitHub-Hookshot/7a06a51 /api/webhook POST 500 222 B 188 ms GitHub-Hookshot/7a06a51 5a98609500ff02f1584296b1f40001737e6769746875622d6865616c74682d73746167696e670001323031383033303174303131373538000100
A  TypeError: Cannot read property 'login' of null 
A      at Object.handleStatus (/srv/build/server/controllers/webhook-events.js:15:77) 
A      at githubHookRouter.post (/srv/build/server/apis/github-webhook.js:39:51) 
A      at <anonymous>

**Comment by gauntface** [comment]
Do you know the kind of hook or the body of the request?

**Comment by gauntface** [comment]
@samuelli just for future reference, with these kinds of issues if you could include:

1. Repo this occured on
1. Type of hook
1. Hash of the hook
1. Payload of hook

It'll enable me to either dig up the hook details OR re-run the hook and find the error.

**Comment by gauntface** [comment]
I'm gonna close this for now. When it occurs again I'll dig into it with an example payload.
