### ISSUE TITLE
Outgoing PRs don't look at your commits

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#226]
At the moment of writing this issue, https://github.com/Polymer/polymer/pull/5135 is being worked on. The following properties exist:

1. The PR is opened by me
1. The PR has initially been reviewed by @kevinpschaaf
1. The PR has been updated after this review
1. The PR has been assigned to @kevinpschaaf

Per this series of events, I expect this PR to not show up as "Waiting on you" in my health dashboard. Instead, it should be "waiting for kevin", as he is assigned to the PR at the moment.

**Comment by samuelli** [comment]
Hmm that's a good point. We don't look at assignee but for Kevin we would look at the commits that have been made too.

We do show Kevin's correctly:
![image](https://user-images.githubusercontent.com/787668/36914938-ca0cc2b0-1e03-11e8-95d3-bf24e076c159.png)

But are failing to show yours correctly.
