### ISSUE TITLE
"New activity" notification spam

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#227]
![image](https://user-images.githubusercontent.com/787668/36914454-3b7075d4-1e02-11e8-9e66-2d1b3daef193.png)

TTL on new activity notification should be much shorter.

**Comment by samuelli** [comment]
@gauntface: I don't see any TTL since this isn't a push notification. I also tried looking for some shown event so we know if we have to revoke a permission or something. Any ideas?

**Comment by gauntface** [comment]
What would you like the behavior to be?

I was thinking of adding a tag to our notifications so new notifcations replace any currently visible notifications.

Also these should not have a requireInteraction on them, so you shouldn't be seeing more than one ever.
