### ISSUE TITLE
Feature request: requesting changes on a PR should change the item to "no action required"

### ISSUE THREAD

**Issue by notwaldorf** [PolymerLabs/project-health#240]
Not sure if you can detect this, but if I've requested changes on a PR, i'd expect it to see that item a blue "no action required", until the human at the end of the line makes the changes.

**Comment by e111077** [comment]
perhaps we can have a github bot add and remove a `pending response` label?

**Comment by rictic** [comment]
https://github.com/Polymer/polymer-linter/pull/152 is a PR whose current state is "requested changes."

I'd like it to switch back to an orange "needs your review" sorta state if the PR author adds commits or comments to the PR.

**Comment by bicknellr** [comment]
another example: https://github.com/PolymerElements/iron-selector/pull/149
