### ISSUE TITLE
[Feature Request] Color for stale items

### ISSUE THREAD

**Issue by e111077** [PolymerLabs/project-health#241]
We probably should have a "stale item" color for pending response or something that should indicate that you should ping someone. Also would like to set the time period until it is stale

**Comment by samuelli** [comment]
For outgoing or incoming? All the PRs are sorted, so outgoing PRs are sorted by PR creation date. Incoming PRs are sorted by latest activity. That should give a reasonable indication of stale-ness.

**Comment by e111077** [comment]
ah my incoming wasn't available then. I see now; this works!
