### ISSUE TITLE
Polling for orange favicon seems incorrect

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#271]
Staging is different to prod right now with it often switching to orange but I'm pretty sure nothing really changed.

**Comment by samuelli** [comment]
This only seemed to happen around when status checks were failing on one of my PRs. Maybe something changed wrt to auto merge?

**Comment by samuelli** [comment]
Wasn't just outgoing. Whole dashboard flashed.

**Comment by gauntface** [comment]
I updated this on Thursday and this should be fixed. Re-open if it occurs again(but the logic is simplified and should be more reliable).
