### ISSUE TITLE
PR still marked as "Waiting on you" after my last comment

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerLabs/project-health#272]
After sending a commit and commenting on https://github.com/Polymer/polymer-linter/pull/152, my dashboard still displays it as "waiting on you", & "rictic requested changes"
![screen shot 2018-03-08 at 11 07 45 am](https://user-images.githubusercontent.com/6173664/37170877-f9f7b4a0-22c0-11e8-93ec-41bf517c0c59.png)

**Comment by samuelli** [comment]
This is fixed now - based on the presence of a new commit.
