### ISSUE TITLE
Commented on PR, now can't get rid of it

### ISSUE THREAD

**Issue by rictic** [PolymerLabs/project-health#279]
I commented on https://github.com/Polymer/polyserve/pull/135 but since then many others have chimed in, and I'm happy to let them own the review. Is it possible for this to not be one of my reviews? If so, how?

**Comment by rictic** [comment]
Likewise https://github.com/Polymer/polymer-modulizer/pull/165

**Comment by rictic** [comment]
And one more, that's a bit different because I don't have permission on this one: https://github.com/googlearchive/polymer-sublime-plugin/pull/1

**Comment by gauntface** [comment]
@rictic thanks for this (You aren't the only one hitting this)

Commenting on a PR means Github adds you as a reviewer, regardless of whether it makes sense or not.

You can unsubscribe from the PR and it'll remove the entry from the dashboard

![screenshot from 2018-03-12 10-09-53](https://user-images.githubusercontent.com/139760/37298447-8c54f014-25dd-11e8-97aa-d3692169f914.png)

Would that work for you?

**Comment by rictic** [comment]
Yep! That works for me!
