### ISSUE TITLE
Revoke stale notifications

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/project-health#280]
I merged some PRs while at home, but logging into another machine I see stale notifications for the same PRs "*** approved your PR".

**Comment by samuelli** [comment]
How long between approved and seeing this notification? We set a TTL. I don't think we can revoke though, because of the push API, where we have to show a notification on every push event. So we could revoke, but it would have to show something else. cc @gauntface

**Comment by dstockwell** [comment]
I think the push requirement is that the push is "visible to the user", so revoking an existing notification should be sufficient. Although... I guess you might run into problems if the user has already dismissed the notification.

**Comment by gauntface** [comment]
Plan is to add a way that on each new push we'll check if there are any notifications that can be closed.
