### ISSUE TITLE
Choose a contextually relevant favicon when an app failure is detected

### ISSUE THREAD

**Issue by cdata** [PolymerLabs/project-health#322]
## The Problem

The favicon is a 💙. This is awesome and I love it. But it could be more awesome.

## Proposed Behavior

When there is a fatal error in the app (like an unexpected JS exception or a 500 API response), update the favicon to be a 💔.

## Links to Relevant PR's / Issues

N/A

**Comment by gauntface** [comment]
This has been added for bad API responses, it'll turn into a red heart.

**Comment by cdata** [comment]
🎉 🎉 🎉
