### ISSUE TITLE
Add back button on settings page

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#324]
## The Problem

There is no back button on the settings page

![image](https://user-images.githubusercontent.com/5948271/37687457-ec10bec4-2c9b-11e8-8da3-4938dc960415.png)

## Expected Behavior

There is a back button back to the homepage

**Comment by samuelli** [comment]
Dupe of #256

**Comment by TimvdLippe** [comment]
Oh I completely missed that one, sorry!
