### ISSUE TITLE
Delete branch on automerge

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#334]
Seems to be restorable anyway, so not an issue to add this.

**Comment by gauntface** [comment]
Some notes after researching this:

- Using the details of the automerged PR we can get the head reference by adding the following to the GQL query:

```
query CommitToPR($query: String!) {
  pullRequests: search (first: 1, type: ISSUE, query: $query) {
    nodes {
      ... on PullRequest {
        id,
        number,
        title,
        bodyText,
        state,
        url,
        headRef {
          id
          name
          prefix
        }
        repository {
          name
          owner {
            login
          }
        },
        author {
          login
        },
      }
    }
  }
}
```

This will give us:

```
...
          "headRef": {
            "id": "MDM6UmVmMTA4NjA5OTUxOmFzc2lnbmVkLWlzc3Vlcw==",
            "name": "assigned-issues",
            "prefix": "refs/heads/",
          },
...
```

To delete the branch we need to ensure the prefix is `refs/heads/`(i.e. branches on this repo). If it's `refs/tags/` or `refs/remotes/`then we can't delete it.

From this we can delete the request using [this API](https://developer.github.com/v3/git/refs/#delete-a-reference)
