### ISSUE TITLE
Implement popularity

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#363]
Each issue should be given a score based on # comments, # reactions. Reactions should probably be weighted more to encourage reactions more than comments.

To convert to fires, we can start with a fixed scale, eg. a score of 10 = 4 fires. Eventually we can move this to a max observed score per repo and scale accordingly.

**Comment by samuelli** [comment]
Are you going to implement this @gauntface ?

**Comment by samuelli** [comment]
Are you going to delete this?

**Comment by gauntface** [comment]
@samuelli is this needed?
