### ISSUE TITLE
Feature request: wrap every section in a <details> tag

### ISSUE THREAD

**Issue by notwaldorf** [PolymerLabs/project-health#368]
I would like the option to not look at some of the sections, and temporarily hide their contents. I have too many WIP PRs or PRs to other open source libraries that aren't getting reviewed, and they're taking up most of the page even though there's nothing i can do about them.

This is literally everything I see on my dashboard, and none of the items above the fold are actionable:
<img width="1388" alt="screen shot 2018-03-28 at 11 02 38 am" src="https://user-images.githubusercontent.com/1369170/38047552-ca3536c2-3277-11e8-8732-c61d9c83048e.png">

**Comment by gauntface** [comment]
@samuelli is currently working on a filter that will help here, but it may still not be enough.

**Comment by samuelli** [comment]
I'll push out the filter changes which will let you effectively hide the entire contents of the dashboard.

@notwaldorf: let me know how that impacts your use case.

**Comment by notwaldorf** [comment]
A++ would filter again 😂
<img width="1045" alt="screen shot 2018-04-02 at 11 52 59 am" src="https://user-images.githubusercontent.com/1369170/38210497-75e3aec0-366c-11e8-8c96-68aa5f024ca4.png">

**Comment by samuelli** [comment]
Closing this particular issue as I think the filters should suffice here.
