### ISSUE TITLE
Add status failures to "Requires Attention"

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#382]
## The Problem

Whenever there are failed statuses on a PR, I would like to be notified with a "Requires attention" label.

## Expected Behavior

For an open PR, if it has a failing status, I expect the Health board to show "Status failed, check PR status" (or something like that) in orange text, rather than the "Waiting on reviewers".

## Links to Relevant PR's / Issues

https://github.com/PolymerElements/paper-slider/pull/213 failed on Travis and the Health board did not show the status. Would be great if that could be added.

**Comment by samuelli** [comment]
Ahh, that's a good point. We currently only show status checks as failing when the PR is already approved.

**Comment by TimvdLippe** [comment]
This seems to be working now.
![image](https://user-images.githubusercontent.com/5948271/39494136-892e436a-4d95-11e8-85bc-74646c8e1815.png)
