### ISSUE TITLE
Remove settings page

### ISSUE THREAD

**Issue by gauntface** [PolymerLabs/project-health#395]
The current settings page is pretty busted with the new left nav and generally the webhooks / permissions have been confusing.

It should be reconsidered how we allow setting up webhooks etc and the interaction with settings.

**Comment by samuelli** [comment]
I went to redesign the settings page and have now decided that we should remove the settings page entirely.

Push notifications will instead be able to be configured directly from the top right of the main dashboard.

Repos/org webhooks will be configured via separate pages trigged from the nav. I can look into what that flow should be next if you like.

**Comment by samuelli** [comment]
Mocks have been updated with the latest change.

**Comment by gauntface** [comment]
This is has been pretty much cleaned up and all sorted now between Sam's PR and a few follow up PR's
