### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#41]
As part of the action dashboard, push notifications will be critical to the overall UX. Dashboard PRD has more details here, but it'll involve webhooks, user lookup and sending notifications. Most of those pieces are missing today:
 * no webhooks - temporarily we can manually add them per org, while we figure out what the flow is going to be
 * no database - don't yet have a database backing anything. Probably can set up some in-memory store for user info in interim before implementing a proper store.

**Comment by gauntface** [comment]
@samuelli as a very quick and hacky database, we could firebase with public write access to add subscription info.

Regarding webhooks, is it worth investigating a Github App? I suspect we'll want this sooner or later and I'm pretty curious to learn about this.

**Comment by samuelli** [comment]
In memory should probably be fine for now, right? Means you'll have to re-enable each time the server is deployed.

I looked into GitHub apps briefly, summarised at the end here: https://docs.google.com/document/d/1wpb_tO_fUJ7lq-vtFKsGZSjZwJcOi7DcxVDGUrbBTzg/edit#heading=h.9cev405s2ayy My initial interpretation is that it'll make things like the dashboard fairly difficult to use if the app wasn't installed. We may end up wanting some combination into the two, so more research would be great. The webhooks are pretty simple, just some UX questions about permissions etc, since only owners can add them to orgs.

**Comment by gauntface** [comment]
Work for this is done - it's now a case of refinement and figuring out what does and doesn't work.
