### ISSUE TITLE
OAuth app vs GitHub app

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#51]
Just a write up of relevant differences for us and what our final decision is here. I expect we'll mostly want oauth apps for things. 
 
Figure out how this works with setting up org/repo webhooks for push notifications.

**Comment by samuelli** [comment]
GraphQL API not available for GitHub apps right now

**Comment by gauntface** [comment]
# Webhook Setup

To setup the webhook for the developer there are a few options.

- *Developer manually setup*
    - They can just add the webhook to a repo or org on their own (i.e. add https://project-health-test.appspot.com/webhook).
- *Oauth app*
    - We can set the scope of the `https://github.com/login/oauth/authorize` request which we can do repo and / or org level web hook.
    - With this our UI would need to manage permissions for setting the webhook (i.e. developer may need to get the OAuth app granted by org admins).
- *Github App*
    - We can define a webhook and events in the app config and it'll be setup for us on install.

# Access Token
- *Developer manually setup*
    - Personal access token
- *Oauth app*
    - We get this as part of the oauth flow
- *Github app*
    - We can get a user access token by following the same oauth flow as the OAuth app. The only difference is that we need to use a github app client ID and secret. **This does not require the installation of the Github app**. This may however be a token that expires.

**Comment by gauntface** [comment]
Aside: @samuelli pointed out that you can check if a user needs scope permission with:

```
query {
	repository(owner: "PolymerLabs", name: "project-health") {
            viewerCanAdminister
        }
        organization(login: "Polymer") {
            viewerCanAdminister
        }
}
```

**Comment by gauntface** [comment]
@samuelli @aomarks is there anything else you would like to know here?

I'm 100% sold that apps aren't an option unless we want to start doing bot like behavior (i.e. issue management etc).
