### ISSUE TITLE
No Pull Requests section for my Repo?

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/project-health#544]
## The Problem

Information about PRs is no longer available (now there are only two sections "Issues" and "Untriaged Issues").

## Expected Behavior

Outstanding PRs used to be listed, especially those waiting for me to do something.

## Links to Relevant PR's / Issues

I tried to look around and see if the feature set has changed, but I didn't see anything specific. Sorry if I'm holding it wrong.

**Comment by samuelli** [comment]
Looks like we've had some down time which has caused some issues. It should be there and I think if you refresh in a couple of minutes it should be fine.

**Comment by samuelli** [comment]
I think we've fixed the root cause here. Let me know if this becomes an issue again!

**Comment by sjmiles** [comment]
Fwiw, no PR info yet.

**Comment by sjmiles** [comment]
Still no PR info, fwiw.

**Comment by samuelli** [comment]
I'm a bit puzzled by this, I can't reproduce anything and I'm not seeing any particular errors which might be causing this.

**Comment by sjmiles** [comment]
Anything I can do to help?

**Comment by samuelli** [comment]
Are there any console errors? Any failing network requests?

**Comment by sjmiles** [comment]
Nope, nothing obviously amiss. 

I see api requests for `issues/untriaged`, `issues/labels`, and `issues/by-labels`, nothing about PRs (I have no idea if that's meaningful).

**Comment by samuelli** [comment]
I don't think your personal dashboard. Correct URL for your main dashboard is https://github-health.appspot.com/. This will show your pull requests & issues across all repositories on GitHub.

Additionally, from the menu on the left hand side, you can access "projects" (which are repos on GitHub). These pages currently only show issues and not pull requests. This feature request is documented in #470.

**Comment by sjmiles** [comment]
Doh, I was totally holding it wrong. 

A thousand pardons.
