### ISSUE TITLE
Add 'read:org' scope to OAuth permissions

### ISSUE THREAD

**Issue by gauntface** [PolymerLabs/project-health#83]
For the settings UI, we display each orgs name and current state of adminstration rights and webhook being enabled or not.

To get the name of the orgs we need `read:org` scope to be added.

@samuelli can you add this to the application config.

**Comment by gauntface** [comment]
Ignore me - The scopes need assigning in the github authorize call but that needs deploying to be changed.

**Comment by samuelli** [comment]
Yep. We should probably request different scopes. Eg. On first experience I wouldn't want to give org access. But if you're trying to setup orgs, we'll need it then.

**Comment by gauntface** [comment]
Good point!
