### ISSUE TITLE
Dashboard PR scenarios

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#86]
- [x] 1. I create a PR on GitHub, add some reviewers. 
- [x] 2. Someone has requested my review on a new pull request.
- [ ] 3. Someone has requested my review on a new pull request, with multiple reviewers. 
- [x] 4. I am a reviewer, have commented but not approved the PR. 
- [x] 5. I requested changes on a PR and there have been new commits.
- [x] 6. I approved changes on a PR and there have been new comments or commits on the PR.
- [ ] 7. I approved changes on a PR, status checks passed and PR author does not have merge access. #302 
- [x] 8. I am a reviewer on a pull request and I was @mentioned in a comment.
- [x] 9. I submitted a review for a PR with no new activity.

**Comment by gauntface** [comment]
> 3. Someone has requested my review on a new pull request, with multiple reviewers.

Add a mark against the title highlighting that it's been approved by someone else

> 7. I approved changes on a PR, status checks passed and PR author does not have merge access.

Check if the author has commit access and call out if they dont and force other team members to perform the merge (Being pulled out into seperate issue.

**Comment by gauntface** [comment]
Punting remaining points to external issues and prioritize accordingly.
